version: "3"
services:
  openldap:
    container_name: openldap
    image: osixia/openldap:1.5.0-amd64
    restart: always
    ports:
      - 389:389
      - 636:636
    volumes:
      - ./openldap:/etc/localtime
      - ./openldap/data:/var/lib/ldap
      - ./openldap/conf:/etc/ldap/slapd.d
    environment:
      LDAP_TLS_VERIFY_CLIENT: never
      LDAP_ORGANISATION: git
      LDAP_DOMAIN: git.com.cn
      LDAP_ADMIN_PASSWORD: G1T@Ldap
      LDAP_CONFIG_PASSWORD: G1T@Ldap

    networks:
      - openldap
    deploy:
      resources:
        limits:
           memory: 1G
        reservations:
           memory: 1G

  phpldapadmin:
    container_name: phpldapadmin
    image: osixia/phpldapadmin:0.9.0-amd64
    restart: always
    links:
      - openldap
    depends_on:
      - openldap
    ports:
      - 8099:80
    volumes:

    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=https://phpldapadmin-lesstop.cloud.okteto.net
      - PHPLDAPADMIN_HTTPS=True
    networks:
      - openldap
    deploy:
      resources:
        limits:
           memory: 1G
        reservations:
           memory: 256M

networks:
  openldap:
